[package]
name = "wrapped_mono"
version = "0.1.0"
edition = "2021"
links = "mono-2.0"
[build-dependencies]
#bindgen = "0.60.1" #uncoment to enable bind regeneration
[dependencies]
macros = {path = "src/macros"}

[dev-dependencies]
rusty-fork = "0.3.0"
[workspace]
members = ["src/macros"]
[features]
#Specifies if a custom link
#custom_link_path =[]

